export const INDIAN_COLLEGES = [
  // IITs
  "Indian Institute of Technology Bombay (IITB)",
  "Indian Institute of Technology Delhi (IITD)",
  "Indian Institute of Technology Madras (IITM)",
  "Indian Institute of Technology Kanpur (IITK)",
  "Indian Institute of Technology Kharagpur (IITKGP)",
  "Indian Institute of Technology Roorkee (IITR)",
  "Indian Institute of Technology Guwahati (IITG)",
  "Indian Institute of Technology Hyderabad (IITH)",
  "Indian Institute of Technology Indore (IITI)",
  "Indian Institute of Technology Gandhinagar (IITGN)",
  "Indian Institute of Technology Ropar (IITRPR)",
  "Indian Institute of Technology Patna (IITP)",
  "Indian Institute of Technology Bhubaneswar (IITBBS)",
  "Indian Institute of Technology Jodhpur (IITJ)",
  "Indian Institute of Technology (BHU) Varanasi",
  "Indian Institute of Technology Palakkad (IITPKD)",
  "Indian Institute of Technology Tirupati (IITTP)",
  "Indian Institute of Technology Goa (IIT Goa)",
  "Indian Institute of Technology Jammu (IIT Jammu)",
  "Indian Institute of Technology Dharwad (IITDh)", 
  // NITs
  "National Institute of Technology Tiruchirappalli (NITT)",
  "National Institute of Technology Karnataka, Surathkal (NITK)",
  "National Institute of Technology Warangal (NITW)",
  "National Institute of Technology Rourkela (NITRKL)",
  "National Institute of Technology Calicut (NITC)",
  "National Institute of Technology Durgapur (NITDGP)",
  "National Institute of Technology Kurukshetra (NITKKR)",
  "National Institute of Technology Allahabad (MNNIT)",
  "National Institute of Technology Silchar (NITS)",
  "National Institute of Technology Jaipur (MNIT)",
  "National Institute of Technology Jalandhar (NITJ)",
  "National Institute of Technology Hamirpur (NITH)",
  "National Institute of Technology Meghalaya (NITM)",
  "National Institute of Technology Patna (NITP)",
  "National Institute of Technology Raipur (NITRR)",
  "National Institute of Technology Agartala (NITA)",
  // IIITs
  "Indian Institute of Information Technology Allahabad (IIITA)",
  "Indian Institute of Information Technology Hyderabad (IIITH)",
  "Indian Institute of Information Technology Bangalore (IIITB)",
  "Indian Institute of Information Technology Gwalior (IIITM)",
  "Indian Institute of Information Technology Design & Manufacturing Kancheepuram (IIITDM Kancheepuram)",
  "Indian Institute of Information Technology Design & Manufacturing Jabalpur (IIITDMJ)",
  "Indian Institute of Information Technology Kota (IIITK)",
  "Indian Institute of Information Technology Guwahati (IIITG)",
  "Indian Institute of Information Technology Vadodara (IIITV)",
  // Other Prominent Universities & Colleges
  "University of Delhi (DU)",
  "Jawaharlal Nehru University (JNU)",
  "Banaras Hindu University (BHU)",
  "Aligarh Muslim University (AMU)",
  "Anna University, Chennai",
  "Vellore Institute of Technology (VIT)",
  "Birla Institute of Technology and Science, Pilani (BITS Pilani)",
  "Manipal Institute of Technology (MIT)",
  "PSG College of Technology, Coimbatore",
  "Thapar Institute of Engineering and Technology, Patiala",
  "College of Engineering, Pune (COEP)",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "Indraprastha Institute of Information Technology, Delhi (IIITD)",
  "Jadavpur University, Kolkata",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "SRM Institute of Science and Technology, Chennai",
  "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar",
  "Lovely Professional University (LPU), Phagwara",
  "Christ University, Bangalore",
  "Symbiosis International University, Pune",
  "Narsee Monjee Institute of Management Studies (NMIMS), Mumbai",
  "Xavier Labour Relations Institute (XLRI), Jamshedpur",
  "Indian School of Business (ISB), Hyderabad/Mohali",
  "Tata Institute of Social Sciences (TISS), Mumbai",
  "National Law School of India University (NLSIU), Bangalore",
  "All India Institute of Medical Sciences (AIIMS), Delhi",
  "Christian Medical College (CMC), Vellore",
  "Armed Forces Medical College (AFMC), Pune",
  "Lady Shri Ram College For Women (LSR), Delhi",
  "Miranda House, Delhi",
  "Hindu College, Delhi",
  "St. Stephen\'s College, Delhi",
  "Loyola College, Chennai",
  "Presidency University, Kolkata",
  "Mount Carmel College, Bangalore",
  "Fergusson College, Pune",
  "St. Xavier\'s College, Mumbai",
  "Indian Statistical Institute (ISI), Kolkata"
] as const; 